name: Build

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: heyframe/github-actions/.github/workflows/build-zip.yml@main
    with:
      extensionName: '${{ github.event.repository.name }}'
